CREATE USER 'simpleticket2'@'%' IDENTIFIED BY '123';
CREATE DATABASE simpleticket2 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON simpleticket2.* TO 'simpleticket2'@'%';
FLUSH PRIVILEGES;

